#!/bin/bash
mynet="192.168.1"
mydomain="myhost.com"
ntpserver="192.168.1.149"
dnsserver="192.168.1.149"
yum -y install augeas dhcp-server
cat > /tmp/dhcpdconfig << EOF
defvar mypath /files/etc/dhcp/dhcpd.conf
set \$mypath
set \$mypath/#comment[1]  "DHCP Server Configuration file."
set \$mypath/#comment[2]  "see /usr/share/doc/dhcp-server/dhcpd.conf.example"
set \$mypath/#comment[3]  "see dhcpd.conf(5) man page"
set \$mypath/#comment[4]  "This config file is generated by augeas"
set \$mypath/subnet
set \$mypath/subnet/network  "$mynet.0"
set \$mypath/subnet/netmask  "255.255.255.0"
set \$mypath/subnet/range
set \$mypath/subnet/range/from  "$mynet.21"
set \$mypath/subnet/range/to  "$mynet.200"
set \$mypath/subnet/option[1]
set \$mypath/subnet/option[1]/domain-name-servers
set \$mypath/subnet/option[1]/domain-name-servers/arg  "$dnsserver"
set \$mypath/subnet/option[2]
set \$mypath/subnet/option[2]/domain-name
set \$mypath/subnet/option[2]/domain-name/arg  \'"$mydomain"\'
set \$mypath/subnet/option[3]
set \$mypath/subnet/option[3]/ntp-servers
set \$mypath/subnet/option[3]/ntp-servers/arg  "$ntpserver"
set \$mypath/subnet/option[4]
set \$mypath/subnet/option[4]/routers
set \$mypath/subnet/option[4]/routers/arg  "$mynet.1"
set \$mypath/subnet/option[5]
set \$mypath/subnet/option[5]/broadcast-address
set \$mypath/subnet/option[5]/broadcast-address/arg  "$mynet.255"
set \$mypath/subnet/default-lease-time  "600"
set \$mypath/subnet/max-lease-time  "7200"
set \$mypath/#comment[5] "host rh82 {"
set \$mypath/#comment[6] "hardware ethernet 00:0c:29:ae:a3:9b;"
set \$mypath/#comment[7] "server-name rh82;"
set \$mypath/#comment[8] "fixed-address 192.168.14.111;"
set \$mypath/#comment[9] "filename \"vmunix.passacaglia\";"
set \$mypath/#comment[10] "}"
save
EOF

augtool -s -f /tmp/dhcpdconfig
sed   -e "s/'$mydomain'/$mydomain/g"  /etc/dhcp/dhcpd.conf
systemctl enable dhcpd
systemctl restart  dhcpd
firewall-cmd --permanent --add-service=dhcp
firewall-cmd --reload
