apiVersion: apps/v1
kind: Deployment
metadata:
  name: emptydir
spec:
  selector:
    matchLabels:
      app: emptydir
  template:
    metadata:
      labels:
        app: emptydir
    spec:
      volumes:
        - name: mydir
          emptyDir: {}
      
      containers:
      - name: one
        image: busybox
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
          - name: mydir
            mountPath: /foo
        command:
          - "/bin/sh"
        args:
          - "-c"
          - "sleep 1000"
      - name: two
        image: busybox
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
          - name: mydir
            mountPath: /foo
        command:
          - "/bin/sh"
        args:
          - "-c"
          - "touch /foo/t2 && sleep 1000"