apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp3
  annotations:
    labels: mylabel02
spec:
  replicas: 10
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1  
      maxSurge: 1    
  selector:
    matchLabels:
      app: myapp3
  template:
    metadata:
      labels:
        app: myapp3
    spec:
      containers:
      - name: myapp3
        image: amigoscode/kubernetes:hello-world-v2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
#/api/v1/customer
#/health