apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostpath
spec:
  selector:
    matchLabels:
      app: hostpath
  template:
    metadata:
      labels:
        app: hostpath
    spec:
      volumes:
        - name: mydir
          hostPath:
            path: /var/log
            
      
      containers:
      - name: one
        image: busybox
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
          - name: mydir
            mountPath: /foo
            readOnly: true
        command:
          - "/bin/sh"
        args:
          - "-c"
          - "sleep 1000"
 