apiVersion: batch/v1
kind: Job
metadata:
  name: myjob
spec:
  ttlSecondsAfterFinished: 30
  template:
    spec:
      containers:
      - name: myjob
        image: busybox
        command: ["/bin/sh" , "-c"]
        args:
          - "echo 'performing backup...' && sleep 20"
      restartPolicy: Never
